# Generated by Django 2.0.2 on 2018-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(default=-1, verbose_name='Note list ID')),
                ('header', models.CharField(max_length=140, verbose_name='Name')),
                ('body', models.CharField(max_length=1024, verbose_name='Contents')),
                ('date', models.DateTimeField(verbose_name='Creation date')),
            ],
        ),
    ]
